version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
  say-hello-ignore-dev:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say Hello Besides dev branch"
          command: "echo Hello, Everybody Besides DEV"
workflows:
  say-hello-workflow:
    jobs:
      - say-hello:
         filters:
           branches:
             only: dev
  say-hello-ignore-dev-workflow:
    jobs:
      - say-hello-ignore-dev:
         filters:
           branches:
             ignore: dev
