version: 2.1

jobs:
  build-and-push-docker-image:
    docker:
      - image: cimg/go:1.17
        auth:
          username: beksultancs
          password: NeverForgotYourPassword
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          cd circleci-example
          docker build -t beksultancs/circleci:$TAG .
          echo this is password $DOCKER_PASS
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push beksultancs/circleci:$TAG
       
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
          
workflows:
  build-and-push-docker-image-workflow:
    jobs:
      - build-and-push-docker-image:
          filters:
            branches:
              only: dev
      - say-hello
