version: 2.1

orbs: 
  eb: circleci/aws-elastic-beanstalk@2.0.1

jobs:
  build-and-push-docker-image:
    docker:
      - image: cimg/go:1.17
        auth:
          username: beksultancs
          password: NeverForgotYourPassword
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          cd circleci-example
          docker build -t beksultancs/circleci:$TAG .
          echo NeverForgotYourPassword | docker login -u beksultancs --password-stdin
          docker push beksultancs/circleci:$TAG

  deploy-to-aws-elastic-beanstalk:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - eb/setup
      - run:
          name: "Insert Beks to docker-compose.yml and deploy using eb cli"
          command: |
            sed -i -e "s;%BEKS%;$CIRCLE_BUILD_NUM;g" ./circleci-example/Dockerrun.aws.json
            cd ./circleci-example && eb init $AWS_APPLICATION_NAME -r $AWS_DEFAULT_REGION -p docker
            eb deploy

workflows:
  deploy:
    jobs:
      - build-and-push-docker-image:
          filters:
            branches:
              only: dev
      - deploy-to-aws-elastic-beanstalk:
          context:
            - CIRCLECI-CONTEXT
          filters:
            branches:
              only: dev
          requires:
            - build-and-push-docker-image
        

